[providers]
    [providers.coingecko]
        name="coingecko"
        currencies = [
            "usd",
            "btc",
            "eth",
            "eur"
        ]
        base_route = "https://api.coingecko.com/api/v3"
        [providers.coingecko.routes]
            ping = "/ping"
            simple_price = "/simple/price"
            coins_history = "/coins/{id}/history"
        [providers.coingecko.coins]
            storm="stmx"
            bitcoin="btc"
            iotex="iotx"
            quark-chain="qkc"
            chiliz="chz"
            cardano="ada"
            avalanche-2="avax"
            basic-attention-token="bat"

            