[providers]
    [providers.coingecko]
        name="coingecko"
        currencies = [
            "usd",
            "btc",
            "eth",
            "eur"
        ]
        base_route = "https://api.coingecko.com/api/v3"
        [providers.coingecko.routes]
            ping = "/ping"
            simple_price = "/simple/price"
            coins_history = "/coins/{id}/history"
        [providers.coingecko.coins]
            storm="stmx"
            bitcoin="btc"
            iotex="iotx"
            quark-chain="qkc"
            chiliz="chz"
            cardano="ada"
            avalanche-2="avax"
            basic-attention-token="bat"
            ethereum="eth"
            sushi="sushi"
            ripple="xrp"
            zilliqa="zil"
            "0x"="zrx"
            dogecoin="doge"
            uniswap="uni"
            litecoin="ltc"
            bitcoin-cash="bch"
            tron="trx"
            chainlink="link"
            vechain="vet"
            matic-network="matic"
            status="snt"
            yearn-finance="yfi"
            aave="aave"
            balancer="bal"
            stellar="xlm"
            compound-coin="comp"
            havven="snx"
            tether="usdt"
            curve-dao-token="crv"
            golem="glm"
            aion="aion"
            keep3rv1="kp3r"
            binancecoin="bnb"
            swipe="sxp"
            republic-protocol="ren"
            zcash="zec"
            dash="dash"
            district0x="dnt"
            enjincoin="enj"
            fio-protocol="fio"
            ardor="ardr"
            ankr="ankr"
            the-graph="grt"
            polkadot="dot"
            filecoin="fil"
            pancakeswap-token="cake"
            terra-luna="luna"
            maker="mkr"
            wazirx="wrx"
            leash="leash"
            
